const $SoundEvents = Java.loadClass('net.minecraft.sounds.SoundEvents')
const $ParticleTypes = Java.loadClass('net.minecraft.core.particles.ParticleTypes')

StartupEvents.registry('fluid', event => {
  event.create('utopia:liquid_oxygen')
    .displayName('Liquid Oxygen')
    .tint(0xAFEEEE)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
      //.addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_WATER, 'minecraft:water_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_WATER)
    )
    .noBlock()

  event.create('utopia:liquid_hydrogen')
    .displayName('Liquid Hydrogen')
    .tint(0xFFFFFF)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
      //.addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_WATER, 'minecraft:water_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_WATER)
    )
    .noBlock()

  event.create('utopia:liquid_nitrogen')
    .displayName('Liquid Nitrogen')
    .tint(0xE0F7FA)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
    )
    .noBlock()

  event.create('utopia:ammonia')
    .displayName('Ammonia')
    .tint(0x9D4EDD)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
    )
    .noBlock()

  event.create('utopia:nitric_acid')
    .displayName('Nitric Acid')
    .tint(0x8B4513)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
    )
    .noBlock()

  event.create('utopia:bleach')
    .displayName('Bleach')
    .tint(0x39FF14)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
    )
    .bucketItem.texture('utopia:item/bleach')

  event.create('utopia:propylene_glycol')
    .displayName('Propylene Glycol')
    .tint(0x36454F)
    .type(type => type
      .renderType(3)
      .stillTexture('kubejs:block/gas_still')
      .flowingTexture('kubejs:block/gas_flow')
      .fallDistanceModifier(0)
    )
    .noBlock()
    .bucketItem.texture('utopia:item/propylene_glycol')
})