const $SoundEvents = Java.loadClass('net.minecraft.sounds.SoundEvents')
const $ParticleTypes = Java.loadClass('net.minecraft.core.particles.ParticleTypes')

StartupEvents.registry('fluid', event => {
  event.create('utopia:oxygen')
    .displayName('Oxygen')
    .tint(0xAFEEEE)
    .type(type => type
      .renderType(3)
      .fallDistanceModifier(0)
      //.addDripstoneDripping(1, $ParticleTypes.DRIPPING_DRIPSTONE_WATER, 'minecraft:water_cauldron', $SoundEvents.POINTED_DRIPSTONE_DRIP_WATER)
    )
    .stillTexture('kubejs:block/gas_still')
    .flowingTexture('kubejs:block/gas_flow')
    .translucent()
    .noBlock()
    .noBucket()
    .tag('utopia:gas')

  event.create('utopia:hydrogen')
    .displayName('Hydrogen')
    .tint(0xFFFFFF)
    .type(type => type
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/gas_still')
    .flowingTexture('kubejs:block/gas_flow')
    .translucent()
    .noBlock()
    .noBucket()
    .tag('utopia:gas')

  event.create('utopia:nitrogen')
    .displayName('Nitrogen')
    .tint(0xE0F7FA)
    .type(type => type
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/gas_still')
    .flowingTexture('kubejs:block/gas_flow')
    .translucent()
    .noBlock()
    .noBucket()
    .tag('utopia:gas')

  event.create('utopia:ammonia')
    .displayName('Ammonia')
    .tint(0x9D4EDD)
    .slopeFindDistance(3)
    .type(type => type
      .screenOverlayTexture('kubejs:block/soupy_overlay')
      .density(2000).viscosity(3000)
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/gas_still')
    .flowingTexture('kubejs:block/gas_flow')
    .translucent()
    .noBlock()
    .noBucket()
    .tag('utopia:gas')

  event.create('utopia:nitric_acid')
    .displayName('Nitric Acid')
    .tint(0x8B4513)
    .slopeFindDistance(3)
    .type(type => type
      .screenOverlayTexture('kubejs:block/soupy_overlay')
      .density(2000).viscosity(2500)
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/watery_still').flowingTexture('kubejs:block/watery_flow')
    .translucent()
    .noBlock()
    .noBucket()

  event.create('utopia:bleach')
    .displayName('Bleach')
    .tint(0x14ff6a)
    .slopeFindDistance(3)
    .type(type => type
      .screenOverlayTexture('kubejs:block/soupy_overlay')
      .density(1500).viscosity(3000)
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/watery_still').flowingTexture('kubejs:block/watery_flow')
    .translucent()
    .levelDecreasePerBlock(2)
    .slopeFindDistance(2)
    .tickRate(10)
    .bucketItem
      .texture('utopia:item/bleach_bucket')


  event.create('utopia:glue')
    .displayName('Glue')
    .tint(0x61f238)
    .type(type => type
      .screenOverlayTexture('kubejs:block/soupy_overlay')
      .renderType(3)
      .fallDistanceModifier(0.5)
      
    )
    .stillTexture('kubejs:block/glue_still').flowingTexture('kubejs:block/glue_flow')
    .translucent()
    .levelDecreasePerBlock(4)
    .slopeFindDistance(2)
    .tickRate(30)
    .bucketItem
      .texture('utopia:item/glue_bucket')

  event.create('utopia:propylene_glycol')
    .slopeFindDistance(2)
    .displayName('Propylene Glycol')
    .tint(0x36454F)
    .type(type => type
      .screenOverlayTexture('kubejs:block/soupy_overlay')
      .density(2500).viscosity(5000)
      .renderType(3)
      .fallDistanceModifier(0)
    )
    .stillTexture('kubejs:block/soupy_still').flowingTexture('kubejs:block/soupy_flow')
    .translucent()
    .noBlock()
    .noBucket()
})