
global.MAXFOODSIZE = 16;
ItemEvents.modification(event => {
    const itemsToProcess = [
        "minecraft:enchanted_golden_apple",
        "minecraft:baked_potato",
        "minecraft:poisonous_potato",
        "minecraft:beetroot",
        "minecraft:beef",
        "minecraft:cooked_beef",
        "minecraft:porkchop",
        "minecraft:cooked_porkchop",
        "minecraft:mutton",
        "minecraft:cooked_mutton",
        "minecraft:chicken",
        "minecraft:cooked_chicken",
        "minecraft:rabbit",
        "minecraft:cooked_rabbit",
        "minecraft:cod",
        "minecraft:cooked_cod",
        "minecraft:salmon",
        "minecraft:cooked_salmon",
        "minecraft:tropical_fish",
        "minecraft:pufferfish",
        "minecraft:bread",
        "minecraft:cookie",
        "minecraft:cake",
        "minecraft:pumpkin_pie",
        "supplementaries:pancake",
        "supplementaries:candy",
        "minecraft:rotten_flesh",
        "minecraft:spider_eye",
        "minecraft:mushroom_stew",
        "minecraft:beetroot_soup",
        "minecraft:rabbit_stew",
        "minecraft:suspicious_stew",
        "minecraft:honey_bottle",
        "minecraft:ominous_bottle",
        "brewinandchewin:flaxen_cheese_wheel",
        "brewinandchewin:flaxen_cheese_wedge",
        "brewinandchewin:scarlet_cheese_wheel",
        "brewinandchewin:scarlet_cheese_wedge",
        "brewinandchewin:vegetable_omelet",
        "brewinandchewin:creamy_onion_soup",
        "brewinandchewin:cheesy_pasta",
        "brewinandchewin:horror_lasagna",
        "brewinandchewin:scarlet_pierogi",
        "brewinandchewin:fiery_fondue_pot",
        "brewinandchewin:fiery_fondue",
        "brewinandchewin:quiche",
        "brewinandchewin:pizza_slice",
        "brewinandchewin:ham_and_cheese_sandwich",
        "brewinandchewin:kimchi",
        "brewinandchewin:jerky",
        "brewinandchewin:pickled_pickles",
        "brewinandchewin:kippers",
        "brewinandchewin:cocoa_fudge",
        "brewinandchewin:sweet_berry_jam",
        "brewinandchewin:glow_berry_marmalade",
        "brewinandchewin:apple_jelly",
        "farmersdelight:cabbage",
        "farmersdelight:tomato",
        "farmersdelight:onion",
        "farmersdelight:fried_egg",
        "farmersdelight:tomato_sauce",
        "farmersdelight:raw_pasta",
        "farmersdelight:cabbage_leaf",
        "farmersdelight:minced_beef",
        "farmersdelight:beef_patty",
        "farmersdelight:chicken_cuts",
        "farmersdelight:cooked_chicken_cuts",
        "farmersdelight:bacon",
        "farmersdelight:cooked_bacon",
        "farmersdelight:cod_slice",
        "farmersdelight:cooked_cod_slice",
        "farmersdelight:salmon_slice",
        "farmersdelight:cooked_salmon_slice",
        "farmersdelight:mutton_chops",
        "farmersdelight:cooked_mutton_chops",
        "farmersdelight:ham",
        "farmersdelight:smoked_ham",
        "farmersdelight:pie_crust",
        "farmersdelight:apple_pie",
        "farmersdelight:sweet_berry_cheesecake",
        "farmersdelight:chocolate_pie",
        "farmersdelight:cake_slice",
        "farmersdelight:apple_pie_slice",
        "farmersdelight:sweet_berry_cheesecake_slice",
        "farmersdelight:chocolate_pie_slice",
        "farmersdelight:pumpkin_pie_slice",
        "farmersdelight:sweet_berry_cookie",
        "farmersdelight:barbecue_stick",
        "farmersdelight:nether_salad",
        "farmersdelight:mixed_salad",
        "farmersdelight:fruit_salad",
        "farmersdelight:glow_berry_custard",
        "farmersdelight:melon_popsicle",
        "farmersdelight:honey_cookie",
        "farmersdelight:egg_sandwich",
        "farmersdelight:chicken_sandwich",
        "farmersdelight:hamburger",
        "farmersdelight:bacon_sandwich",
        "farmersdelight:mutton_wrap",
        "farmersdelight:dumplings",
        "farmersdelight:stuffed_potato",
        "farmersdelight:bone_broth",
        "farmersdelight:kelp_roll_slice",
        "farmersdelight:cooked_rice",
        "farmersdelight:kelp_roll",
        "farmersdelight:cod_roll",
        "farmersdelight:salmon_roll",
        "farmersdelight:cabbage_rolls",
        "farmersdelight:beef_stew",
        "farmersdelight:chicken_soup",
        "farmersdelight:vegetable_soup",
        "farmersdelight:fish_stew",
        "farmersdelight:fried_rice",
        "farmersdelight:pumpkin_soup",
        "farmersdelight:baked_cod_stew",
        "farmersdelight:roasted_mutton_chops",
        "farmersdelight:mushroom_rice",
        "farmersdelight:pasta_with_mutton_chop",
        "farmersdelight:pasta_with_meatballs",
        "farmersdelight:bacon_and_eggs",
        "farmersdelight:onion_soup",
        "farmersdelight:noodle_soup",
        "farmersdelight:vegetable_noodles",
        "farmersdelight:steak_and_potatoes",
        "farmersdelight:ratatouille",
        "farmersdelight:squid_ink_pasta",
        "farmersdelight:grilled_salmon",
        "farmersdelight:roast_chicken_block",
        "farmersdelight:roast_chicken",
        "farmersdelight:gleaming_salad_block",
        "farmersdelight:shepherds_pie",
        "farmersdelight:shepherds_pie_block",
        "farmersdelight:honey_glazed_ham",
        "farmersdelight:honey_glazed_ham_block",
        "farmersdelight:stuffed_pumpkin",
        "farmersdelight:stuffed_pumpkin_block",
        "farmersdelight:gleaming_salad",
        "farmersdelight:rice_roll_medley_block",
        "farmersdelight:dog_food",
        // "naturalist:cooked_bushmeat",
        // "naturalist:bushmeat",
        // "naturalist:cooked_duck",
        // "naturalist:duck",
        // "naturalist:cooked_venison",
        // "naturalist:venison",
        // "naturalist:cooked_lizard_tail",
        // "naturalist:lizard_tail",
        // "naturalist:bass",
        // "naturalist:cooked_bass",
        "create:bar_of_chocolate",
        "create:sweet_roll",
        "create:chocolate_glazed_berries",
        "create:honeyed_apple",
        "create:builders_tea"
    ]

    let procStarting = 0
    let procAltered = 0
    itemsToProcess.forEach(itemId => {
        let itemStack = Item.of(itemId)
        if (!itemStack.isEmpty()) {
            procStarting++
            if (itemStack.maxStackSize > 16) {
                event.modify(itemId, item => {
                    item.maxStackSize = global.MAXFOODSIZE
                    procAltered++
                })
            }

        }
    })
   console.log("[Utopia] Altering stacks --- Total items to check: " + procStarting + " - Stacks altered to 16: " + procAltered + ".")
})
