#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 26 06:19:39 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=ComplementaryReimagined_r5.8.1.zip
