#Range: 0 ~ 11
newFrontierShape = 0
#Range: 3 ~ 999
newFrontierVertexCount = 16
#Range: 0 ~ 999
newFrontierShapeWidth = 10
#Range: 0 ~ 999
newFrontierShapeRadius = 20
#Range: 0 ~ 7
newFrontierChunkShape = 0
#Range: 0 ~ 32
newFrontierChunkShapeWidth = 5
#Range: 0 ~ 32
newFrontierChunkShapeLength = 5
#Allowed Values: Vertex, Chunk
newFrontierMode = "Vertex"
#Allowed Values: Info, Edit, Nothing
afterCreatingFrontier = "Info"
pasteName = false
pasteVisibility = true
pasteColor = true
pasteBanner = true
pasteOptionsVisible = false
#Force all frontier to be shown or hidden. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
frontierVisibility = "Custom"
#Force all frontier to be announced in chat. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
announceInChat = "Custom"
#Force all frontier to be announced as a title. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
announceInTitle = "Custom"
#Force all frontier to be shown or hidden on the fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenVisibility = "Custom"
#Force all frontier names to be shown or hidden on the fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenNameVisibility = "Custom"
#Force all frontier owners to be shown or hidden on the fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenOwnerVisibility = "Custom"
#Force all frontier banners to be shown or hidden on the fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenBannerVisibility = "Custom"
#Force all frontier to be shown or hidden on the day fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenDayVisibility = "Custom"
#Force all frontier to be shown or hidden on the night fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenNightVisibility = "Custom"
#Force all frontier to be shown or hidden on the underground fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenUndergroundVisibility = "Custom"
#Force all frontier to be shown or hidden on the topo fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenTopoVisibility = "Custom"
#Force all frontier to be shown or hidden on the biome fullscreen map. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
fullscreenBiomeVisibility = "Custom"
#Force all frontier to be shown or hidden on the minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapVisibility = "Custom"
#Force all frontier names to be shown or hidden on the minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapNameVisibility = "Custom"
#Force all frontier owners to be shown or hidden on the minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapOwnerVisibility = "Custom"
#Force all frontier banners to be shown or hidden on the minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapBannerVisibility = "Custom"
#Force all frontier to be shown or hidden on the day minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapDayVisibility = "Custom"
#Force all frontier to be shown or hidden on the night minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapNightVisibility = "Custom"
#Force all frontier to be shown or hidden on the underground minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapUndergroundVisibility = "Custom"
#Force all frontier to be shown or hidden on the topo minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapTopoVisibility = "Custom"
#Force all frontier to be shown or hidden on the biome minimap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
minimapBiomeVisibility = "Custom"
#Force all frontier to be shown or hidden on the webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapVisibility = "Custom"
#Force all frontier names to be shown or hidden on the webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapNameVisibility = "Custom"
#Force all frontier owners to be shown or hidden on the webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapOwnerVisibility = "Custom"
#Force all frontier banners to be shown or hidden on the webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapBannerVisibility = "Custom"
#Force all frontier to be shown or hidden on the day webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapDayVisibility = "Custom"
#Force all frontier to be shown or hidden on the night webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapNightVisibility = "Custom"
#Force all frontier to be shown or hidden on the underground webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapUndergroundVisibility = "Custom"
#Force all frontier to be shown or hidden on the topo webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapTopoVisibility = "Custom"
#Force all frontier to be shown or hidden on the biome webmap. In Custom you can decide for each frontier.
#Allowed Values: Custom, Always, Never
webmapBiomeVisibility = "Custom"
#Duration of title announcement, in game ticks.
#Range: 0 ~ 1200
titleAnnouncementDuration = 70
#Minimum time between consecutive title announcement, in game ticks.
#Range: 0 ~ 1200
titleAnnouncementTimeout = 0
#Show the frontier announcement above the hotbar instead of showing it as a title.
titleAnnouncementAboveHotbar = false
#Announce unnamed frontiers in chat/title.
announceUnnamedFrontiers = false
#Distance at which vertices are attached to nearby vertices.
#Range: 0 ~ 16
snapDistance = 8
sendCommand = "msg"
#Hides the name if it is wider than the frontier at the zoom level it is being viewed.
hideNamesThatDontFit = true
#Transparency of the frontier polygons. 0.0 is fully transparent and 1.0 is opaque.
#Range: 0.0 ~ 1.0
polygonsOpacity = 0.4
#Width of the frontier border.
#Range: 0 ~ 64
borderWidth = 0
#Transparency of the frontier border. 0.0 is fully transparent and 1.0 is opaque.
#Range: 0.0 ~ 1.0
borderOpacity = 1.0
#Size of the frontier text.
#Range: 1 ~ 5
textSize = 2
#Transparency of the frontier text. 0.0 is fully transparent and 1.0 is opaque.
#Range: 0.0 ~ 1.0
textOpacity = 1.0
#Color of the frontier text. Frontier will use the frontier color. Bright will also use the same color but with maximum brightness.
#Allowed Values: Frontier, Bright, White
textColor = "Frontier"
#Size of the frontier banner.
#Range: 1 ~ 5
bannerSize = 1
#Transparency of the frontier banner. 0.0 is fully transparent and 1.0 is opaque.
#Range: 0.0 ~ 1.0
bannerOpacity = 1.0
#Show buttons on fullscreen map.
fullscreenButtons = true
#Show a confirmation dialog before deleting a frontier.
askConfirmationFrontierDelete = true
#Show a confirmation dialog before deleting a group.
askConfirmationGroupDelete = true
#Show a confirmation dialog before deleting an user.
askConfirmationUserDelete = true
#Order of the frontier list sorting modes.
frontierSorting = ["Created", "Name", "Owner", "VertexChunk", "Area", "Modified"]
#Direction of the frontier list sorting modes. True means ascending and false means descending.
frontierSortingDirection = [false, true, true, true, true, false]
#Allowed Values: All, Global, Personal
filterFrontierType = "All"
#Allowed Values: All, You, Others
filterFrontierOwner = "All"
filterFrontierDimension = "all"

[hud]
	#Show the HUD on screen.
	enabled = true
	#Automatically switch to nearest anchor when HUD position is edited (on settings screen).
	autoAdjustAnchor = true
	#Automatically snap to closest border when HUD position is edited (on settings screen).
	snapToBorder = true
	#Size of the HUD text.
	#Range: 1 ~ 8
	textSize = 1
	#Size of the HUD banner.
	#Range: 1 ~ 8
	bannerSize = 3
	#HUD element on slot 1.
	#Allowed Values: None, Name, Owner, Banner
	slot1 = "Name"
	#HUD element on slot 2.
	#Allowed Values: None, Name, Owner, Banner
	slot2 = "Owner"
	#HUD element on slot 3.
	#Allowed Values: None, Name, Owner, Banner
	slot3 = "Banner"
	#Anchor point of the HUD. In the case of choosing the minimap as an anchor, its default position will be used as a reference in the coordinates.
	#Allowed Values: ScreenTop, ScreenTopRight, ScreenRight, ScreenBottomRight, ScreenBottom, ScreenBottomLeft, ScreenLeft, ScreenTopLeft, Minimap, MinimapHorizontal, MinimapVertical
	anchor = "MinimapHorizontal"
	#Range: > -2147483648
	xPosition = 0
	#Range: > -2147483648
	yPosition = 0
