version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
oreganized = true
streamsreflowing = true
farmersdelight = true
barteringstation = true
createtransmission = true
someassemblyrequired = true
alexsmobs = true
storagedrawers = true
easymagic = true
brewinandchewin = true
easyanvils = true
etched = true
quark = true
alexscaves = true
sable_player_ragdoll = true
refurbished_furniture = true
diy_campfires = true
comforts = true
citadel = true
escalated = true
bits_n_bobs = true
nirvana = true
stockmarket = true
createcobblestone = true
parcool = true
moonlight = true
utopia = true
treechop = true
tradeworks = true
exposure = true
endanchor = true
naturalist = true
supplementaries = true
backpacked = true
create_vibrant_vaults = true
create_confectionery = true
create = true
frame_changer = true
sereneseasons = true
createadditionallogistics = true
struts = true
minecraft = true
azimuth = true
create_dragons_plus = true
unusual_furniture = true
create_connected = true
endermanoverhaul = true
creeperoverhaul = true
create_bb = true
reliable_backpacks = true
create_power_loader = true
