[Animation]
	enable = true
	enable_camera_animation = true

	[Animation.Availability]
		"parcool:fast_run" = true
		"parcool:crawl" = true
		"parcool:dodge_right" = true
		"parcool:dodge_front" = true
		"parcool:dodge_back" = true
		"parcool:hang_on" = true
		"parcool:climb_up" = true
		"parcool:climb_up_jump" = true
		"parcool:trick_jump_back" = true
		"parcool:trick_jump_forward" = true
		"parcool:stride" = true
		"parcool:slide_down" = true
		"parcool:breakfall_no_move" = true
		"parcool:breakfall_forward" = true
		"parcool:horizontal_wall_run" = true
		"parcool:slide" = true
		"parcool:dive" = true
		"parcool:skydive" = true
		"parcool:dive_in_air" = true
		"parcool:skydive_in_air" = true
		"parcool:dive_into_water" = true
		"parcool:jump_charging" = true
		"parcool:charge_jump" = true
		"parcool:vault_forward" = true
		"parcool:vault_side" = true
		"parcool:wall_jump" = true
		"parcool:hide_in_block_stand" = true
		"parcool:hide_in_block_crawl" = true
		"parcool:hang_down" = true
		"parcool:hang_down_jump_forward" = true
		"parcool:hang_down_jump_backward" = true
		"parcool:ride_zipline" = true
		"parcool:wall_run" = true
		"parcool:castaway" = true
		"parcool:pole_climb" = true
		"parcool:fast_swim" = true
		"parcool:grapple" = true
		"parcool:creative_fly" = true
