["Client revive settings"]
	#Revive timer X offset
	# Default: 0
	# Range: > -2147483648
	reviveOffsetX = 0
	#Revive timer Y offset
	# Default: 0
	# Range: > -2147483648
	reviveOffsetY = 0
	#Give up timer X offset
	# Default: 0
	# Range: > -2147483648
	giveUpOffsetX = 0
	#Give up timer Y offset
	# Default: 0
	# Range: > -2147483648
	giveUpOffsetY = 0
