#Truly Dark properties file
#Wed Aug 26 06:19:40 EDT 2026
biome_blacklist=
cloud_darkness=0.1
dark_default=false
dark_end=false
dark_end_fog=0.0
dark_moon=false
dark_nether=false
dark_nether_fog=0.5
dark_overworld=true
dark_sky=false
dark_skyless=false
entity_light_floor=0.03
fog_darkness=0.0
hard_lock=false
ignore_moon_phase=false
moon_phase_intensity=1.0
only_affect_block_light=false
pack_configured=false
require_client_mod=false
setup_version=Manual
sky_darkness=0.1
sky_merge=true
